### ISSUE TITLE
undefined in "searchResults" but present in "rawResults"

### ISSUE THREAD

**Issue by florianmatz** [lucaong/minisearch#88]
Hi Luca,

me again^^

I have the following, quite strange behaviour.

You can add entries to the list of elements, that can be searched with mini-search.
While you add the new entry, the query stays active. 

The result should be, if the new entry matches the query, it should be displayed.

So, if the input data changes I perform search via a useEffect hook and display the new data.

But what happens is that despite having a match in the raw results (correct field, correct match, everything ok), the entry in searchResult is undefined causing a crash.

```ts
   useEffect(() => {
        if (data && !isFirstRender.current) {
            removeAll();
            addAll(data);
        }

        isFirstRender.current = false;

    }, [data]);

    useEffect(() => {
        if (data) {
            search(filter.query, {
                filter: filterOptions.categoryField && filter.categories.length > 0 ? matchCategory : undefined,
            });
        }
    }, [data, filter, filterOptions, matchCategory]);

```

The order of execution is correct, double checked on that.

Result looks like:

rawResults
```ts
[
    {
        "id": "6a901953144c411580520ed07B4567",
        "terms": [
            "einholung"
        ],
        "score": 8.600445452294665,
        "match": {
            "einholung": [
                "custom.bezeichnung"
            ]
        },
        "custom.kategorien": [
            "Gefahr in Verzug",
            "Sicherheit",
            "Qualität"
        ]
    },
    {
        "id": "h1662s",
        "terms": [
            "einholungsbums"
        ],
        "score": 4.152082359120152,
        "match": {
            "einholungsbums": [
                "custom.bezeichnung"
            ]
        },
        "custom.kategorien": [
            "Gefahr in Verzug"
        ]
    }
]
```

```ts
[
    {
        "id": "6a901953144c411580520ed07B4567",
        "datum": "2020-09-17T20:34:56.170914Z",
        "custom": {
            "id": "6a901953144c411580520ed07a21ef39",
            "erstelldatum": "2020-09-17T20:34:56.170914Z",
            "baumassnahmenId": "45042621",
            "bezeichnung": "Einholung weiterer Informationen",
            "kategorien": [
                "Gefahr in Verzug",
                "Sicherheit",
                "Qualität"
            ],
    .....
    },
    undefined -> Where the second element should be.
]

```

Help would be highly appreciated. I'm kind of confused...

**Comment by lucaong** [comment]
I did find a small bug with `removeAll` in `react-minisearch`, fixed in the latest release, but I think it's not what causes your issue. You can try out the latest version of `react-minisearch` though (`3.0.2`), and let me know.

**Comment by florianmatz** [comment]
Hi Luca. Just updated the package. Still the same results concerning the difference between `searchResults` and `rawResults` (having still one undefined in `searchResults`).

As a quickfix I just filter out the undefined item in the `searchResults` and reset the query and categories when data changes.

But still, kind of strange, isn't it? Obviously there is a match, but the item does not get mapped back to searchResults?

**Comment by lucaong** [comment]
Definitely strange. I am sure the problem lies with react-minisearch (not with MiniSearch itself), but I don’t know what causes it.

Did you notice anything specific about the documents that are missing from the results but present in the rawResults?

**Comment by florianmatz** [comment]
Hi Luca, sorry for the late response. 

No, not at all. Tried it with different datasets, always the same behaviour. Do you need a Fiddle for further investigation?

**Comment by lucaong** [comment]
if possible, a Fiddle reproducing the issue would be awesome.

**Comment by florianmatz** [comment]
Hi Luca:

Here you go: https://codepen.io/florianmatz/pen/xxqEaGE?

Steps to reproduce:

- Codepen's console
- Enter "Zum Testen" into the search field ("Enter query")
- You'll get a "No results" warning
- Now switch the dataset; choose "Dataset 1" from select
- App crashes -> discrepancy between rawResults and searchResults (see console) as described in the issue

What's completely weird:

If you switch the datasets BEFORE you perform the reproduction steps, it works like a charm. So, what's important to repdroduce: Only with data, that has not been indexed before... So make sure you've reloaded the codepen before testing it.

Here you find a short screen recording, if my description was to confusing... :)
https://we.tl/t-3Xpiz6bMq6

**Comment by lucaong** [comment]
thanks a lot, that's really useful! I should be able to dedicate some time to it soon, and hopefully get to the bottom of this

**Comment by florianmatz** [comment]
Cool! Looking forward to it. Hoping it's not just some kind of my stupidity that costs you time^^

Btw, the download links is only valid for 7 days.

**Comment by lucaong** [comment]
Great news @florianmatz ,
the problem was indeed caused by [`react-minisearch`](https://github.com/lucaong/react-minisearch) using `useState` instead of `useRef` to store local values, and therefore causing unnecessary re-rendering which would happen in between state updates.

The new version 3.0.3 of [`react-minisearch`](https://github.com/lucaong/react-minisearch) fixes the problem, and seems to work well with your app: https://codepen.io/lucaong/pen/yLMVxxy

Thanks again for reporting this! I am closing the issue, but feel free to comment on it if you find out that it is not completely solved.
